site_name: MySite
theme:
  name: material
  features:
    - content.action.view
    - navigation.footer
  palette:
    media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: 'deep orange'
    accent: 'amber'
