site_name: MySite
theme:
  name: material
  features:
    - content.action.view
    - navigation.footer
    - navigation.path
    - navigation.top
  palette:
    media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: 'teal'
    accent: 'teal'
