nav: 
  - Welcome: index.md
  - Cluster: clusters 
  - user-docs/account-registration.md
  - user-docs/quickstart.md
  - Tutorials: tutorials
  - Guides: guides
  - Software Modules: 
    - software-modules/environment-modules.md
    - software-modules/*.md
  - Policies: policies
  
