nav: 
  - Welcome: index.md
  - Clusters: clusters 
  - account-registration.md
  - quickstart.md
  - Tutorials: tutorials
  - Guides: guides
  - References: references
  - Software Modules: 
    - software-modules/environment-modules.md
    - software-modules/*.md
  - Policies: policies
  
